-- ลบข้อมูลเดิมและเพิ่มใหม่ทั้งหมด
DELETE FROM room_teachers;

INSERT INTO room_teachers (teacher_id, classroom_id, is_primary)
SELECT t.id, c.id, true FROM teachers t, classrooms c WHERE
(t.username='sanchai' AND c.room_name='ม.1/1')
OR (t.username='palop' AND c.room_name='ม.1/1')
OR (t.username='ariya' AND c.room_name='ม.1/2')
OR (t.username='wittawat.wg' AND c.room_name='ม.1/2')
OR (t.username='jaturong' AND c.room_name='ม.1/3')
OR (t.username='tanakom' AND c.room_name='ม.1/4')
OR (t.username='warangkana' AND c.room_name='ม.1/4')
OR (t.username='priyakorn' AND c.room_name='ม.2/1')
OR (t.username='bodin' AND c.room_name='ม.2/1')
OR (t.username='tikamporn' AND c.room_name='ม.2/2')
OR (t.username='bunsong' AND c.room_name='ม.2/2')
OR (t.username='chalermpol' AND c.room_name='ม.2/3')
OR (t.username='pongsakorn' AND c.room_name='ม.2/3')
OR (t.username='lakkika' AND c.room_name='ม.2/4')
OR (t.username='pongtep' AND c.room_name='ม.2/4')
OR (t.username='chatchai' AND c.room_name='ม.3/1')
OR (t.username='satit' AND c.room_name='ม.3/1')
OR (t.username='sujitra' AND c.room_name='ม.3/2')
OR (t.username='ittiporn' AND c.room_name='ม.3/2')
OR (t.username='jantiwaporn' AND c.room_name='ม.3/3')
OR (t.username='noppamas' AND c.room_name='ม.3/3')
OR (t.username='chayaphat' AND c.room_name='ม.3/4')
OR (t.username='patiwat' AND c.room_name='ม.3/4')
OR (t.username='siriporn' AND c.room_name='ม.4/1')
OR (t.username='koraphat' AND c.room_name='ม.4/1')
OR (t.username='theerapong' AND c.room_name='ม.4/2')
OR (t.username='amonrat' AND c.room_name='ม.4/2')
OR (t.username='surachai' AND c.room_name='ม.4/3')
OR (t.username='phubet' AND c.room_name='ม.4/3')
OR (t.username='uthumporn' AND c.room_name='ม.4/4')
OR (t.username='songkran' AND c.room_name='ม.4/4')
OR (t.username='adisak' AND c.room_name='ม.5/1')
OR (t.username='disnon' AND c.room_name='ม.5/1')
OR (t.username='ananya' AND c.room_name='ม.5/2')
OR (t.username='anong' AND c.room_name='ม.5/3')
OR (t.username='theerisa' AND c.room_name='ม.5/3')
OR (t.username='jatuporn' AND c.room_name='ม.5/4')
OR (t.username='tananya' AND c.room_name='ม.5/4')
OR (t.username='malinee' AND c.room_name='ม.6/1')
OR (t.username='jittipong' AND c.room_name='ม.6/1')
OR (t.username='hannarong' AND c.room_name='ม.6/2')
OR (t.username='wanichaya' AND c.room_name='ม.6/2')
OR (t.username='wittawat.kh' AND c.room_name='ม.6/3')
OR (t.username='phantong' AND c.room_name='ม.6/3')
OR (t.username='amora' AND c.room_name='ม.6/4')
OR (t.username='napat' AND c.room_name='ม.6/4');